gfc:
  ip: 127.0.0.1
  swagger:
    enabled: true
    title: 用户认证中心
    description: 用户认证中心接口文档
    version: 1.0
    base-package: com.tckj.wx.application.controller

server:
  port: 8888
  tomcat:
    protocol_header: x-forwarded-proto
    remote_ip_header: x-forwarded-for

logging:
  level:
    org:
      springframework:
        web: debug

spring:
  application:
    name: wx-device
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true



mybatis-plus:
  mapper-locations: classpath:/mybatis-mappers/*Mapper.xml
  typeAliasesPackage: com.tckj.wx.application.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



wx:
  appid: wx1a0d82b7f96f1d6021234
  secret: 55460bb709aefa43ce733ae7b30044bd